### ISSUE TITLE
Filter Allowed Characters Undocumented

### ISSUE THREAD

**Issue by CodeLenny** [bminer/node-blade#209]
I found out that filters can't include `$` the hard way.

```blade
:$my-filter
  test
```

I would think that filter names could contain a larger subset of characters, but perhaps there's some other limitation I'm not aware of.

Either way, it would be nice if the documentation might describe the allowed characters.  It appears the parser is limited to:

```
first_char: [a-zA-Z_]
next_chars: [a-zA-Z0-9_:-]*
```

**Comment by bminer** [comment]
I could change the parser to allow dollar sign `$` in the identifier name.  I am hesitant to add it to the parser because the `identifier` lexer rule is used for tag names, class names, attribute names, etc.   Not sure how `:` colon made the cut either... come to think of it.

But... at the same time, I can't really argue much against it.  It probably won't break anything, so I'll just ahead and add it for now.

**Comment by CodeLenny** [comment]
@bminer Thanks!
